const DashboardStyles = {
  container: "min-h-screen flex flex-col md:flex-row bg-gradient-to-br from-gray-50 via-white to-gray-100 dark:from-gray-900 dark:via-gray-900 dark:to-gray-800",
  mobileToggle: "flex md:hidden justify-between items-center bg-gradient-to-r from-green-600 to-emerald-600 text-white px-4 py-3 shadow-lg fixed top-0 left-0 right-0 z-50",
  mobileTitle: "text-xl font-bold tracking-tight",
  toggleButton: "focus:outline-none p-2 rounded-lg hover:bg-white/20 transition-colors duration-200",
  toggleIcon: "text-xl",
  // Sidebar with mobile backdrop and dark mode
  sidebar: "bg-white/95 dark:bg-gray-800/95 backdrop-blur-md text-gray-700 dark:text-gray-200 w-72 py-6 px-5 shadow-xl flex flex-col justify-between transition-all duration-300 ease-in-out border-r border-gray-200/50 dark:border-gray-700 fixed md:relative h-full z-40 top-0 left-0",
  sidebarBackdrop: "fixed inset-0 bg-black/50 backdrop-blur-sm z-30 md:hidden transition-opacity duration-300",
  logoContainer: "flex items-center justify-center py-4 mb-8 mt-12 md:mt-0",
  logoImage: "w-10 h-10 md:w-12 md:h-12 drop-shadow-md",
  logoText: "text-xl md:text-2xl font-bold bg-gradient-to-r from-green-600 to-emerald-600 bg-clip-text text-transparent ml-3",
  nav: "space-y-2 flex-1",
  navLink: "flex items-center py-3 px-4 rounded-xl transition-all duration-300 text-gray-600 dark:text-gray-300 hover:bg-gradient-to-r hover:from-green-50 hover:to-emerald-50 dark:hover:from-green-900/30 dark:hover:to-emerald-900/30 hover:text-green-700 dark:hover:text-green-400 hover:shadow-sm hover:translate-x-1 group",
  navIcon: "mr-3 text-gray-400 dark:text-gray-500 group-hover:text-green-600 dark:group-hover:text-green-400 transition-colors duration-300 text-lg",
  navText: "text-sm md:text-base font-medium",
  activeLink: "bg-gradient-to-r from-green-100 to-emerald-100 dark:from-green-900/40 dark:to-emerald-900/40 text-green-700 dark:text-green-400 shadow-sm",
  sidebarFooter: "self-end flex flex-col items-center py-4 md:py-6 border-t border-gray-200 dark:border-gray-700 mt-4 w-full",
  credits: "text-sm font-semibold text-green-600 dark:text-green-400 bg-green-50 dark:bg-green-900/30 px-3 py-1 rounded-full",
  avatarContainer: "cursor-pointer transform hover:scale-105 transition-transform duration-200",
  avatarImage: "w-12 h-12 md:w-14 md:h-14 rounded-full border-3 border-green-200 dark:border-green-700 shadow-lg mb-3 object-cover",
  userInfo: "text-center",
  userName: "text-sm font-semibold text-gray-800 dark:text-gray-100",
  userEmail: "text-xs text-gray-500 dark:text-gray-400 mt-0.5",
  userCard: "absolute left-4 md:left-20 bottom-28 md:bottom-32 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl shadow-2xl p-4 md:p-5 z-50 min-w-56 md:min-w-64 animate-fadeIn",
  cardHeader: "flex items-center mb-3 pb-3 border-b border-gray-100 dark:border-gray-700",
  cardAvatar: "w-12 h-12 md:w-14 md:h-14 rounded-full border-2 border-green-200 dark:border-green-700 mr-3 object-cover shadow-md",
  cardUserName: "font-semibold text-gray-800 dark:text-gray-100 text-sm md:text-base",
  cardUserEmail: "text-xs md:text-sm text-gray-500 dark:text-gray-400",
  mainContent: "flex-1 p-4 md:p-8 lg:p-10 text-gray-800 dark:text-gray-100 bg-transparent min-h-screen mt-14 md:mt-0",
};

export default DashboardStyles;
