const DashboardStyles = {
  container: "min-h-screen flex flex-col md:flex-row bg-gradient-to-br from-gray-50 via-white to-gray-100",
  mobileToggle: "flex md:hidden justify-between items-center bg-gradient-to-r from-green-600 to-emerald-600 text-white px-4 py-3 shadow-lg",
  mobileTitle: "text-2xl font-bold tracking-tight",
  toggleButton: "focus:outline-none p-2 rounded-lg hover:bg-white/20 transition-colors duration-200",
  toggleIcon: "text-2xl",
  sidebar: "bg-white/90 backdrop-blur-sm text-gray-700 w-72 py-6 px-5 shadow-xl flex flex-col justify-between transition-all duration-300 ease-in-out border-r border-gray-200/50 fixed md:relative h-full z-50",
  logoContainer: "flex items-center justify-center py-4 mb-8",
  logoImage: "w-12 h-12 drop-shadow-md",
  logoText: "text-2xl font-bold bg-gradient-to-r from-green-600 to-emerald-600 bg-clip-text text-transparent ml-3",
  nav: "space-y-2 flex-1",
  navLink: "flex items-center py-3 px-4 rounded-xl transition-all duration-300 text-gray-600 hover:bg-gradient-to-r hover:from-green-50 hover:to-emerald-50 hover:text-green-700 hover:shadow-sm hover:translate-x-1 group",
  navIcon: "mr-3 text-gray-400 group-hover:text-green-600 transition-colors duration-300 text-lg",
  navText: "text-base font-medium",
  activeLink: "bg-gradient-to-r from-green-100 to-emerald-100 text-green-700 shadow-sm",
  sidebarFooter: "self-end flex flex-col items-center py-6 border-t border-gray-200 mt-4 w-full",
  credits: "text-sm font-semibold text-green-600 mb-3 bg-green-50 px-3 py-1 rounded-full",
  avatarContainer: "cursor-pointer transform hover:scale-105 transition-transform duration-200",
  avatarImage: "w-14 h-14 rounded-full border-3 border-green-200 shadow-lg mb-3 object-cover",
  userInfo: "text-center",
  userName: "text-sm font-semibold text-gray-800",
  userEmail: "text-xs text-gray-500 mt-0.5",
  userCard: "absolute left-20 bottom-32 bg-white border border-gray-200 rounded-xl shadow-2xl p-5 z-50 min-w-64 animate-fadeIn",
  cardHeader: "flex items-center mb-3 pb-3 border-b border-gray-100",
  cardAvatar: "w-14 h-14 rounded-full border-2 border-green-200 mr-3 object-cover shadow-md",
  cardUserName: "font-semibold text-gray-800",
  cardUserEmail: "text-sm text-gray-500",
  mainContent: "flex-1 p-8 md:p-10 text-gray-800 bg-transparent min-h-screen md:ml-0",
};

export default DashboardStyles;
